### ISSUE TITLE
Add linting tooling to CONTRIBUTING.md

### ISSUE THREAD

**Issue by UniquePixels** [TheOdinProject/.github#23]
I think it would be a good idea to add a section to the style guide about installing and using local listing tools as an optional item.

**Comment by JoshDevHub** [comment]
Thank you for making this issue @fabulousgk 

Do you have any thoughts about what tooling should be listed?

**Comment by UniquePixels** [comment]
I am using the VSCode plugin https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint which requires no further configuration and picks up the config in the curriculum repo automatically.  It will catch everything but the heading layouts.  This is a great option for getting most the issues.

Then I also installed markdownlint-cli2 as a global npm package so that I could specify a config file for the headings.  

- `markdownlint-cli2 --config ./lesson.markdownlint-cli2.jsonc ./path_to_file` for lessons 
- `markdownlint-cli2 --config ./project.markdownlint-cli2.jsonc ./path_to_file` for projects.

**Comment by JoshDevHub** [comment]
Awesome @fabulousgk 

I agree something should be done with this. Imo a big problem happens when a user is a first time contributor. Every time they push new commits, they have to get approval before the actions will run. This leads to things like this happening:
- new contributor opens a new PR. lint doesn't run because workflows need maintainer approval.
- maintainer opens the PR and approves the workflow run so lint, spellcheck, etc. start up.
- maintainer or CI tools spot errors that new contributor needs to fix.
- new contributor pushes a partial fix for some of the problems.
- the new contributor has now lost lint information. Before they can see it again, the workflow must be approved *again* by a maintainer.

This all makes their workflow very reliant on a maintainer quickly responding to their work, which is bad. Having a way to run these checks locally would be a huge help.

You're thinking of adding some instructions around [here](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#top-curriculum-repo) in CONTRIBUTING.md, right?

An important thing to call out for using the CLI: learners aren't going to be able to do that until they're past the [node.js install lesson](https://www.theodinproject.com/lessons/foundations-installing-node-js) in Foundations (which kinda sucks).

**Comment by JoshDevHub** [comment]
I wonder if there's a way to configure the vscode plugin such that it properly understands when to use lesson or project configs. Here's a link to it's [configuration interface](https://github.com/DavidAnson/vscode-markdownlint/tree/main?tab=readme-ov-file#configure).

It's not immediately jumping out to me how this could be done in a way where it understands to pull the lesson or project config based on the filename, but maybe we can play around with it some and figure something out. If we find something works, we can create a `.vscode` file in the curriculum repo that configures the extension in a particular way, and then all contributors would have to do is download the extension. Not 100% this will be possible though.

**Comment by UniquePixels** [comment]
Perhaps something with custom rules https://github.com/DavidAnson/vscode-markdownlint/tree/main?tab=readme-ov-file#markdownlintcustomrules

Maybe the answer is moving the project/lesson stuff into a custom rule entirely?

**Comment by JoshDevHub** [comment]
We can definitely try exploring it some. In the meantime feel free to put in a PR for this that:
- Mentions the vscode plugin. Note that because we have some custom rules setup, it won't perfectly catch everything
- Mentions the CLI. Note that this will be perfectly accurate, but will require node installation

Good to have something up that helps people, then we can think about a way to make it better.

**Comment by UniquePixels** [comment]
I will open a new discusstion in the curriculum repo to discuss the possible changes we talked about to improve the plugin.
